import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {useSession, signIn, signOut, getSession} from "next-auth/react";
import Account from "@/pages/account";
import Typography from "@mui/material/Typography";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Account/>
      </main>
    </>
  )
}

export async function getServerSideProps({ req } : { req: any }) {
    const session = await getSession({ req });

    if (!session) {
        return {
            redirect: {
                destination: '/signIn',
                permanent: false,
            }
        }
    }

    return {
        props: { session }
    }
}
